🐛 : Assigning to __pdoc__ caused internal error (AttributeError: 'bool' object has no attribute 'expandtabs') so revert to docstring on module var.